---
services:

  # Jellyfin proxy 
  nginx:
    image: nginx:latest 
    container_name: jellyfin-proxy
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jellyfin
    restart: unless-stopped
    networks:
      - torrent_network

  jellyfin:
    image: jellyfin/jellyfin:latest  # You can specify a version like '10.8.0' if needed
    container_name: jellyfin
    environment:
      - PUID=1000  # Set to the user ID on your host system
      - PGID=1000  # Set to the group ID on your host system
      - TZ=Europe/London  # Set the timezone
    volumes:
      - ./jellyfin-config:/config  # Configuration files and data
      - ./jellyfin-cache:/cache    # Cache location
      - /mnt/content/server/:/media    # Media files (movies, tv shows, music)
    ports:
      - "8096:8096"  # Web UI port (default Jellyfin port)
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri  # For hardware transcoding (if available)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - torrent_network



  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge

    networks: 
      - torrent_network 
        #ipv4_address: 172.20.0.6
    depends_on:
      - protonvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
      - DELUGE_PASSWORD=password

    volumes:
      - /root/docker-media-server/deluge-config:/config
      - /mnt/content/server/downloads:/downloads
      - /mnt/content/server/shows:/downloads/shows
      - /mnt/content/server/movies:/downloads/movies
      - /mnt/content/server/games:/downloads/games
      
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
        #network_mode: "service:protonvpn"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks: 
        - torrent_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/lib/radarr:/config
      - /mnt/content/server/movies:/movies #optional
        #- /path/to/download-client-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
        #- RUN_OPTS= #optional
    volumes:
      - /root/containers/jackett-config:/config
        #- /dev/null:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks: 
        - torrent_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/lib/sonarr:/config
      - /mnt/content/server/shows:/tv #optional
        #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped


  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - torrent_network
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Etc/UTC
    restart: unless-stopped

  protonvpn:
    image: walt3rl/proton-privoxy 
    container_name: protonvpn
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - PVPN_USERNAME=
      - PVPN_PASSWORD=
    volumes:
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8080
    restart: unless-stopped
    devices:
        - /dev/net/tun
    networks:
      - torrent_network

networks:
  torrent_network:
    driver: bridge 
    external: true

